# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
    workflow_dispatch

# YAML anchors for common steps
x-common-steps: &common-setup
  - name: Checkout code
    uses: actions/checkout@v5.0.0
  - name: Use Node.js 22
    uses: actions/setup-node@v4
    with:
      node-version: '22.x'
      cache: 'npm'

x-restore-cache: &restore-cache
  - name: Restore node_modules
    uses: actions/cache@v4
    with:
      path: node_modules
      key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      <<: *common-setup
      - name: Install dependencies
        run: npm install
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      <<: *common-setup
      <<: *restore-cache
      - name: Build
        run: npm run build

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      <<: *common-setup
      <<: *restore-cache
      - name: Aqua Security Trivy Install
        uses: aquasecurity/setup-trivy@v0.2.3
      - name: Run SAST
        run: npm run audit:trivy
      - name: Archive SAST results
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: report.html
